name: build

on:
  push:
    branches:
      - main
      - 'renovate/**'
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@499789684c9a0d41c9b3f0d66a785ba17b1d51ab # renovate: tag=v1.9.0
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
